export const ICONS = {
  MENU: require('../assets/icons/menu.png'),
  BACK: require('../assets/icons/back.png'),
  MOON: require('../assets/icons/moon.png'),
  MORE: require('../assets/icons/more.png'),
  LOGOUT: require('../assets/icons/power-off.png'),
  SHARE: require('../assets/icons/send.png'),
  SETTING: require('../assets/icons/settings.png'),
  SEARCH: require('../assets/icons/search.png'),
  LIKE: require('../assets/icons/like.png'),
  EYE_OFF: require('../assets/icons/eye-off.png'),
  EYE_ON: require('../assets/icons/eye.png'),
  ERROR: require('../assets/icons/error.png'),
  CORRECT: require('../assets/icons/correct.png'),
  HEADPHONE: require('../assets/icons/headphone.png'),
  CLOSE: require('../assets/icons/close.png'),
  CLOSE_ROUND: require('../assets/icons/close-round.png'),
  PREV: require('../assets/icons/prev.png'),
  NEXT: require('../assets/icons/next.png'),
  PLAY: require('../assets/icons/play.png'),
  STOP: require('../assets/icons/stop.png'),
  VOLUME: require('../assets/icons/volume.png'),
  BIN: require('../assets/icons/bin.png'),
  NO_RESULTS: require('../assets/icons/no-results.png'),
  DOWN_ARROW: require('../assets/icons/down-arrow.png'),
  UP_ARROW: require('../assets/icons/up-arrow.png'),
  HIGH: require('../assets/icons/high.png'),
  LOW: require('../assets/icons/low.png'),
  RIGHT: require('../assets/icons/right.png'),
  TRENDING: require('../assets/icons/trend.png'),
  ABOUT: require('../assets/icons/about.png'),
  INVITE: require('../assets/icons/invite.png'),
  DOWNLOAD: require('../assets/icons/download.png'),
  POLL: require('../assets/icons/poll.png'),
  MAGAZINE: require('../assets/icons/magazine.png'),
  NEWSPAPER: require('../assets/icons/newspaper.png'),
  POLLS: require('../assets/icons/polls.png'),
  PLUS: require('../assets/icons/plus.png'),
  MINUS: require('../assets/icons/minus.png'),
  DRAG: require('../assets/icons/drag.png'),
  STAR: require('../assets/icons/star.png'),
  STAR_FILL: require('../assets/icons/star-fill.png'),
  NEWS: require('../assets/icons/news.png'),
  MAG: require('../assets/icons/mag.png'),
  COUPON: require('../assets/icons/coupon.png'),
  TV: require('../assets/icons/tv.png'),
  PIN: require('../assets/icons/pin.png'),
};

export const EMOJIE = {
  LIKE: {src: require('../assets/icons/like_colored.png'), type: 'LIKE'},
  LOVE: {src: require('../assets/icons/heart.png'), type: 'LOVE'},
  HAHA: {src: require('../assets/icons/laughing.png'), type: 'HAHA'},
  WOW: {src: require('../assets/icons/wow.png'), type: 'WOW'},
  SAD: {src: require('../assets/icons/sad.png'), type: 'SAD'},
};
