export const ICONS = {
  MENU: require('../assets/icons/menu.png'),
  BACK: require('../assets/icons/back.png'),
  MOON: require('../assets/icons/moon.png'),
  MORE: require('../assets/icons/more.png'),
  LOGOUT: require('../assets/icons/power-off.png'),
  SHARE: require('../assets/icons/send.png'),
  SETTING: require('../assets/icons/settings.png'),
  SEARCH: require('../assets/icons/search.png'),
  LIKE: require('../assets/icons/like.png'),
  EYE_OFF: require('../assets/icons/eye-off.png'),
  EYE_ON: require('../assets/icons/eye.png'),
  ERROR: require('../assets/icons/error.png'),
  CORRECT: require('../assets/icons/correct.png'),
  HEADPHONE: require('../assets/icons/headphone.png'),
  CLOSE: require('../assets/icons/close.png'),
  PREV: require('../assets/icons/prev.png'),
  NEXT: require('../assets/icons/next.png'),
  PLAY: require('../assets/icons/play.png'),
  STOP: require('../assets/icons/stop.png'),
  VOLUME: require('../assets/icons/volume.png'),
};
