export const IMAGES = {
  LOGO: require('../assets/images/logo.png'),
  AUDIO: require('../assets/images/audio.jpg'),
  FALLBACK: require('../assets/images/search_fallback.png'),
  CHANNEL: require('../assets/images/channel.jpg'),
  NEWS: require('../assets/images/news.jpg'),
  MAGAZINE1: require('../assets/images/magazine1.jpg'),
  MAGAZINE2: require('../assets/images/magazine2.jpg'),
  MAGAZINE3: require('../assets/images/magazine3.jpeg'),
  NEWSPAPER1: require('../assets/images/Newspaper1.jpg'),
  NEWSPAPER2: require('../assets/images/Newspaper2.jpg'),
  NEWSPAPER3: require('../assets/images/Newspaper3.jpeg'),
  NEWSPAPER4: require('../assets/images/Newspaper4.jpeg'),
  STOCK_BANNER_BG: require('../assets/images/stock-background.jpeg'),
  SPORTS_BANNER_BG: require('../assets/images/sports-background.jpg'),
};
