export const STRINGS = {
  APP_NAME: 'NewsApp',
  TABNAME_1: 'Summary',
  TABNAME_2: 'Headlines',
  DARK_MODE: 'Dark Mode',
  LIGHT_MODE: 'Light Mode',
  PROFILE_SETTINGS: 'Profile Settings',
  CATEGORY: 'Category',
  BUSINESS: 'Business',
  LIFESTYLE: 'Lifestyle',
  SCITECH: 'Sci & Tech',
  AGRO: 'Agro',
  ASTROLOGY: 'Astrology',
  AUTOMOBILE: 'Automobile',
  CRIME: 'Crime',
  CULTURE: 'Culture',
  EDUCATION: 'Education',
  ENTERTAINMENT: 'Entertainment',
  HEALTH: 'Health',
  INDIA: 'India',
  INTERNATIONAL: 'International',
  LATEST_NEWS: 'Latest News',
  POLITICS: 'Politics',
  SPORTS: 'Sports',
  LOGOUT: 'Log Out',
  CANCEL: 'Cancel',
  GET_STARTED: 'Get Started',
  LOGIN_HERE: 'Login Here',
  SIGN_UP_HERE: 'Sign Up Here',
  FORGOT_PASSWORD: 'Forgot Password',
  RESET_PASSWORD: 'Reset Password',
  SAVE: 'Save',
  DELETE: 'Delete',
  EDIT: 'Edit',
  ADD: 'Add',
  REMOVE: 'Remove',
  YES: 'Yes',
  NO: 'No',
  OK: 'OK',
  PLEASE_WAIT: 'Please Wait',
  NO_INTERNET: 'No Internet',
  NO_DATA: 'No Data',
  ERROR: 'Error',
  SUCCESS: 'Success',
  PLEASE_TRY_AGAIN: 'Please Try Again',
  PLEASE_SELECT_CATEGORY: 'Please Select Category',
  PLEASE_ENTER_VALID_EMAIL: 'Please Enter Valid Email',
  PLEASE_ENTER_VALID_PASSWORD: 'Please Enter Valid Password',
  PLEASE_ENTER_VALID_NAME: 'Please Enter Valid Name',
  SUBMIT: 'Submit',
  DONE: 'Done',
};
