export const LIGHT_THEME = {
  BACKGROUND_COLOR: '#ffffff',
  BORDER_COLOR: '#A02334',
  TEXT_COLOR: '#333333',
  BTN_BACKGROUND_COLOR: '#F4DEB3',
  BTN_TEXT_COLOR: '#333333',
  ICON_TINT_COLOR: '#000000',
  TILE_BACKGROUND_COLOR: '#E9EFEC',
  TILE_TEXT_COLOR: '#333333',
  SNACKBAR: '#F4DEB3',
};

export const DARK_THEME = {
  BACKGROUND_COLOR: '#333333',
  BORDER_COLOR: '#ffffff',
  TEXT_COLOR: '#ffffff',
  BTN_BACKGROUND_COLOR: '#E8B86D',
  BTN_TEXT_COLOR: '#333333',
  ICON_TINT_COLOR: '#ffffff',
  TILE_BACKGROUND_COLOR: '#1E201E',
  TILE_TEXT_COLOR: '#ffffff',
  SNACKBAR: '#F4DEB3',
};
